# The python and numpy variants are only used for local conda builds.
# They are overridden by the CI scripts.
python:
  - 3.11

numpy:
  - 1.24

c_compiler:
  - vs2022 # [win]

cxx_compiler:
  - vs2022 # [win]

c_compiler_version:
  - 13 # [linux]

cxx_compiler_version:
  - 13 # [linux]
